apiVersion: v1
kind: Pod
metadata:
  name: init-container 
spec:
  volumes: 
  - name: app-data
    emptyDir: {}
  initContainers:
  - name: delay
    image: busybox
    command: ['sh', '-c' ,'sleep 30']
  - name: download
    image: alpine 
    command: ['sh', '-c', 'apk update; apk add git; git clone -b develop https://github.com/mariano-italiano/lxk_Sep.git /app; echo "Git repo cloned and index.html downloaded" ']
    volumeMounts:
    - name: app-data
      mountPath: /app
  containers:
  - name: web
    image: nginx
    volumeMounts:
    - name: app-data
      mountPath: /usr/share/nginx/html
