apiVersion: v1
kind: Pod
metadata:
  name: web-multi
spec:
  restartPolicy: Never
  containers:
  - name: web1
    image: httpd
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 1d']
