apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
spec:
  containers:
  - image: nginx
    name: web1
    env:
      - name: ENV_VAR1
        valueFrom: 
          configMapKeyRef:
            name: my-configmap
            key: config.json
      - name: CHRONY_CONFIG
        valueFrom:
          configMapKeyRef:
            name: chrony-cm 
            key: chrony.conf
    envFrom:
      - configMapRef:
          name: another-cm 
