apiVersion: v1
kind: Pod
metadata:
  labels:
    run: toleration-pod
  name: toleration-pod
spec:
  containers:
  - image: httpd
    name: toleration-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "zone"
    operator: "Exists"
    effect: "NoSchedule"
